#  ON OFF ,you need restart service after change setting
shell_proxy_default: 'ON'
subscribe_urls:
  - "url1"
  - "url2"

# not use
port: 7890
socks-port: 7891
allow-lan: true
external-controller: 9090
